#!/bin/bash

./cleandist
python -V
python ./setup.py sdist --manifest-only
mv MANIFEST MANIFEST2
echo -ne 'nCOPYING\nCOPYRIGHT\nINSTALL\n' > MANIFEST1
ls Oger/examples/*py >> MANIFEST1
sed -i .bak -e '/feedback_and_external_input/d' -e '/fbflow/d' -e '/hierarchical_esn/d' -e '/narma30_demo_continuous/d' -e '/narma30_demo_network/d' MANIFEST1
rm MANIFEST1.bak
ls mdp/demo/*py >> MANIFEST1
ls mdp/utils/*css >> MANIFEST1
ls mdp/hinet/*css >> MANIFEST1
cat MANIFEST1 MANIFEST2  > MANIFEST
rm -rf MANIFEST1 MANIFEST2 
python ./setup.py sdist --formats=gztar
python ./setup.py bdist_wininst 
