#!/bin/bash

./cleandist
python -V
python ./setup.py sdist --manifest-only
mv MANIFEST MANIFEST2
echo -ne 'nCOPYING\nCOPYRIGHT\nINSTALL\n' > MANIFEST1
ls Engine/examples/*py >> MANIFEST1
ls mdp/demo/*py >> MANIFEST1
ls mdp/utils/*css >> MANIFEST1
ls mdp/hinet/*css >> MANIFEST1
cat MANIFEST1 MANIFEST2  > MANIFEST
rm -rf MANIFEST1 MANIFEST2 
python ./setup.py sdist --formats=gztar
